# Site settings
title: Weihua's personal website
SEOTitle: Weihua的博客 | Weihua Blog
header-img: img/post-bg-desk.jpg
email: zhuweihua2746@hotmail.com
description: "Long term consistency trumps short term intensity"
keyword: "Weihua, Weihua Blog, Weihua的博客, WeihuaZhu, Weihua Zhu, API, Backend, Golang, Python, Product Eng, Product Backend Eng"
url: "http://WeihuaZhu.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/WeihuaZhu/WeihuaZhu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "A Life-long learner"
sidebar-avatar: /img/avatar.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
zhihu_username: weihuazhu
github_username: WeihuaZhu
# facebook_username:  
jianshu_username: zackzhu
#twitter_username: WeihuaZhu




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: weihuazhu

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            # TODO update this 生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    # TODO update this 生成的clientSecret
  repo: weihuazhu.github.io    #仓库名称
  owner: WeihuaZhu    #github用户名
  admin: WeihuaZhu
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'G-GPJZFN2ETT'            # TODO update this Format: UA-xxxxxx-xx
ga_domain: auto               # TODO update this 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Pinterest",
        href: "https://www.pinterest.com/"
    },{
        title: "Plaid",
        href: "https://plaid.com/"
    },{
        title: "Slack",
        href: "https://slack.com/"
    }
]
